---
language: ruby

rvm:
  - 2.1.9
  - 2.3.1

env:
  matrix:
    - PUPPET_GEM_VERSION="~> 4.7.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 4.8.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 4" CHECK=test
    - PUPPET_GEM_VERSION="~> 4" CHECK=rubocop

sudo: false

script: 'SPEC_OPTS="--format documentation" bundle exec rake $CHECK'

matrix:
  fast_finish: true

notifications:
  email: false
