---
language: ruby

rvm:
  - 2.1.9

env:
  matrix:
    - PUPPET_GEM_VERSION="~> 4.7.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 4.8.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 4" CHECK=test
    - PUPPET_GEM_VERSION="~> 4" CHECK=rubocop

sudo: false

before_install:
  - bundle -v
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v

script: 'SPEC_OPTS="--format documentation" bundle exec rake $CHECK'

matrix:
  fast_finish: true

notifications:
  email: false
