---
language: ruby

rvm:
  - 2.1.9

env:
  matrix:
    - PUPPET_GEM_VERSION="~> 4.7.0"
    - PUPPET_GEM_VERSION="~> 4.8.0"
    - PUPPET_GEM_VERSION="~> 4.9.0"
    - PUPPET_GEM_VERSION="~> 4.10.0"
    - PUPPET_GEM_VERSION="~> 4"

sudo: false

before_install:
  - bundle -v
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v

script: 'SPEC_OPTS="--format documentation" bundle exec rake test'

matrix:
  fast_finish: true

notifications:
  email: false
